@baseUrl = http://localhost:4004/odata/v4/leave
@employeeId = 00000000-0000-0000-0000-000000000002

@employeeAuth = Basic employee@company.com:123456
@managerAuth = Basic manager@company.com:123456

# Setelah step 2.1 berhasil, copy ID dari response lalu paste di sini
@leaveRequestId = b9e119ab-2aff-4d60-9604-c13480ca2e97


### 2.1 - Direct Create Business Draft
POST {{baseUrl}}/LeaveRequests
Authorization: {{employeeAuth}}
Content-Type: application/json

{
  "Reason": "Case 2 - Direct submit then approve",
  "Employee_ID": "{{employeeId}}",
  "Status": "Drafted",
  "RequestDate": "2026-05-05T09:00:00Z"
}


### 2.2 - Read Created Data
GET {{baseUrl}}/LeaveRequests(ID='{{leaveRequestId}}',IsActiveEntity=true)


### 2.3 - Submit Leave Request
POST {{baseUrl}}/LeaveRequests(ID='{{leaveRequestId}}',IsActiveEntity=true)/LeaveService.submit
Authorization: {{employeeAuth}}
Content-Type: application/json

{}


### 2.4 - Read After Submit
### Expected:
### Status = Submitted
### RequestNumber generated
GET {{baseUrl}}/LeaveRequests(ID='{{leaveRequestId}}',IsActiveEntity=true)


### 2.5 - Approve Leave Request
POST {{baseUrl}}/LeaveRequests(ID='{{leaveRequestId}}',IsActiveEntity=true)/LeaveService.approve
Authorization: {{managerAuth}}
Content-Type: application/json

{
  "Comments": "Case 2 approved after direct submit"
}


### 2.6 - Read Approved Leave Request with Approval History
### Expected:
### Status = Approved
### LeaveApprovals contains Approved history
GET {{baseUrl}}/LeaveRequests(ID='{{leaveRequestId}}',IsActiveEntity=true)?$expand=LeaveApprovals